name: py312
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - anyio=4.6.2
  - aom=3.6.0
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=11.0.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.6.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.1.6
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.11
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.8.185
  - babel=2.14.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blosc=1.21.3
  - bokeh=3.2.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.9.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cartopy=0.24.1
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=3.470
  - cftime=1.6.2
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - cmocean=4.0.3
  - colorama=0.4.6
  - colorcet=3.1.0
  - colorspacious=1.1.2
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=43.0.0
  - curl=8.9.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.2
  - dask=2023.6.1
  - dask-core=2023.6.1
  - datashader=0.16.3
  - datashape=0.5.4
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.6.1
  - docrep=0.3.2
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - flit-core=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - future=1.0.0
  - geos=3.8.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.16.0
  - harfbuzz=4.3.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.16.2
  - httpcore=1.0.9
  - httpx=0.28.1
  - hvplot=0.10.0
  - icu=58.2
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipdb=0.13.13
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipython_genutils=0.2.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.1
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=3.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libarchive=3.6.2
  - libarrow=12.0.1
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.4.2
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.56.2
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libogg=1.3.5
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.20
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzip=1.8.0
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.2
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markdown=3.5.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - msgpack-python=1.0.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mysql=5.7.24
  - natsort=8.2.0
  - nbclassic=1.1.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - netcdf4=1.6.2
  - nettle=3.7.3
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numba=0.60.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpy_groupies=0.11.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - orc=1.7.4
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - panel=1.2.0
  - param=1.13.0
  - parso=0.8.3
  - partd=1.4.1
  - pcre=8.45
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - plotly=5.24.1
  - ply=3.11
  - pooch=1.8.2
  - proj=9.3.1
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pybind11-abi=5
  - pycparser=2.21
  - pyct=0.5.0
  - pyct-core=0.5.0
  - pygments=2.15.1
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyrsistent=0.20.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-lmdb=1.4.1
  - python-tzdata=2023.4
  - pytz=2024.1
  - pyviz_comms=3.0.2
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.32.0
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - s2n=1.3.46
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=75.1.0
  - shapely=2.0.5
  - sip=6.7.12
  - six=1.16.0
  - slicerator=1.1.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tblib=3.0.0
  - tenacity=9.0.0
  - terminado=0.18.0
  - tesseract=5.2.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024b
  - uc-micro-py=1.0.2
  - ucx=1.14.1
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - wcwidth=0.2.12
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - x264=1!157.20191217
  - xarray=2023.6.0
  - xgcm=0.8.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xrft=1.0.0
  - xyzservices=2023.10.1
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
prefix: /glade/u/home/tomasc/miniconda3/envs/py312
