name = "twake"
authors = ["tomchor <tomaschor@gmail.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LambertW = "984bce1d-4616-540c-a9ee-88d1112d94c9"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Oceanostics = "d0ccf422-c8fb-49b5-a76d-74acdde946ac"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TickTock = "9ff05d80-102d-5586-aa04-3a8bd1a90d20"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
